### ISSUE TITLE
product-list.component.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [serhiirubets/angular-mentoring#3]
Свойство encapsulation: ViewEncapsulation.None генерится само по умолчанию или Вы добавили?

**Comment by sergeyamator** [comment]
Само, я использовал angular-cli generate для создания сервисов, компанентов и инициализации проекта

**Comment by VZhyrytskiy** [comment]
Ясно, раньше такого не было, видимо в версии 1.5 изменили описание компонента по молчанию.
